### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by paperbenni** [atbentley/docker-nss-wrapper#1]
Hello, I have a question regarding how to use the image. I tried just referencing it as a from instruction instead of the normal centos image and just let it do its thing. Turns out this doesn't work. I ran my image on openshift and it said:

``no user exists for uid`` _some numbers here_
I did not define an entrypoint by myself so technically my image should inherit the one from your image. Am I wrong with that or is there something else that might potentially be conflicting? Please help me, I already spent way to much time trying to figure out how to get openssh working on openshift!

**Comment by atbentley** [comment]
If my memory serves me right you only inherit the entrypoint of the base
docker image if you don’t specify and command and if you don’t specify an
entrypoint. If you have specified a command you will have no entrypoint.
Can you confirm by explicitly setting your entrypoint to the entrypoint
that my container provides?

**Comment by paperbenni** [comment]
Do I have to declare a user in my Dockerfile for this to work by the way?

**Comment by paperbenni** [comment]
Ok, it randomly decided to work today, no idea what happened. Thanks for the image.
